### ISSUE TITLE
Hi6210sft HwComposer?

### ISSUE THREAD

**Issue by zhaozihanzzh** [XePeleato/HwComposer_Research#1]
I found one from HiKey, I am not sure, but I think it might help:
https://github.com/xin3liang/hwcomposer
Hope this can help you.

**Comment by zhaozihanzzh** [comment]
@XePeleato @Huawei-Dev @hak86 @OldDroid @OpenKirin 
I want an answer…

**Comment by ghost** [comment]
I think is compatible only with lollipop roms and also we should enable drm on kernel to get it work..

**Comment by zhaozihanzzh** [comment]
@hak86 So it is impossible or very hard for 6.0 and above to have a properly working HwComposer?

**Comment by surdu** [comment]
Who summoned me ? :smile:

**Comment by zhaozihanzzh** [comment]
Sorry, I want to @Huawei-Dev …

**Comment by XePeleato** [comment]
@zhaozihanzzh Actually, if you've read the README from my HwC you'd have seen that I've used some code from there.
